"""empty message

Revision ID: a486aebad730
Revises: d45c729eb103
Create Date: 2017-03-09 18:36:54.755524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a486aebad730'
down_revision = 'd45c729eb103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('user_profile', 'userid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user_profile', 'id')
    # ### end Alembic commands ###
