"""empty message

Revision ID: d45c729eb103
Revises: ff14fc3b051a
Create Date: 2017-03-09 18:05:03.242129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd45c729eb103'
down_revision = 'ff14fc3b051a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('userid', sa.Integer(), nullable=False))
    op.drop_column('user_profile', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('user_profile', 'userid')
    # ### end Alembic commands ###
