"""empty message

Revision ID: ff14fc3b051a
Revises: 73893a0f7358
Create Date: 2017-03-02 03:10:16.721172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff14fc3b051a'
down_revision = '73893a0f7358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user_profile', sa.Column('biography', sa.String(length=80), nullable=True))
    op.add_column('user_profile', sa.Column('datejoined', sa.DateTime(), nullable=True))
    op.add_column('user_profile', sa.Column('firstname', sa.String(length=80), nullable=True))
    op.add_column('user_profile', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.add_column('user_profile', sa.Column('lastname', sa.String(length=80), nullable=True))
    op.add_column('user_profile', sa.Column('sex', sa.String(length=6), nullable=True))
    op.drop_column('user_profile', 'first_name')
    op.drop_column('user_profile', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('user_profile', sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('user_profile', 'sex')
    op.drop_column('user_profile', 'lastname')
    op.drop_column('user_profile', 'image')
    op.drop_column('user_profile', 'firstname')
    op.drop_column('user_profile', 'datejoined')
    op.drop_column('user_profile', 'biography')
    op.drop_column('user_profile', 'age')
    # ### end Alembic commands ###
